
export const blogData: BlogData[] = [
    {  id: 1,
        img:'/img/blog5.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: ' Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi.',
       category: 'shipping'
    },
    {  id: 2,
        img:'/img/blog4.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: ' Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi. ',
       category: 'Lifestyle'
    },
    {  id: 3,
        img:'/img/blog3.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: '  Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi.',
       category: 'health'
    },
    {  id: 4,
        img:'/img/blog1.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: ' Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi. ',
       category: 'Lorem'
    },
    {  id: 5,
        img:'/img/blog2.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: '  Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi.',
       category: 'ipsum'
    },
    {  id: 6,
        img:'/img/blog1.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: ' Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi. ',
       category: 'dimensions'
    },
    {  id: 7,
        img:'/img/blog3.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: ' Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi. ',
       category: 'consectetur'
    },
    {  id: 8,
        img:'/img/blog2.svg',
       topic: 'Leo sed pellentesque tortor consequat commodo. Volutpat scelell',
       post: ' Lorem ipsum dolor sit amet consectetur. Pellentesque augue ut commodo ac mi ullamcorper tellus cursus vitae. In quam amet sed mauris laoreet. Vel elit lacus in velit tempus tincidunt tellus quam egestas. Id augue elementum est lacus purus quam tempus viverra. A porttitor integer quam sociis. Turpis nullam nullam a id elit pulvinar. Lectus quam et leo accumsan ullamcorper sed id augue.       Diam viverra sit tortor ultricies sagittis risus tempus. Accumsan est dictum ultrices massa cras fames pretium. Quisque vitae tincidunt egestas nunc lectus turpis purus diam. Integer justo ullamcorper dui eget malesuada mi nec. Mi leo ut neque a. Nibh tincidunt nisi auctor pretium vel odio purus. Mauris neque iaculis egestas nunc id sapien tincidunt quis libero. Amet duis at habitant posuere est pellentesque. Turpis sed odio facilisis et sit interdum ipsum. Integer et urna ac laoreet egestas scelerisque tincidunt tempus. Tortor ipsum massa cursus enim diam pellentesque tincidunt nibh amet. Felis nisl praesent ipsum augue volutpat. Ipsum gravida parturient nisl vel turpis nibh. Nisl lorem lectus mauris vulputate in elit scelerisque varius. Scelerisque nulla ornare leo quisque lectus nisl. Lobortis diam vel vel imperdiet id quis. Enim at nec ullamcorper ac amet augue eu. Suspendisse vel volutpat viverra viverra eu. Eu massa nibh iaculis donec. Pellentesque ac proin odio id massa. Libero integer ac condimentum vitae. Donec nibh dui nibh sit elementum enim. Nisi a elementum magna est purus. Pellentesque nulla ac sed sodales. Nibh ut ultrices vel pulvinar aliquam enim sit. Tincidunt aliquet dapibus duis pretium aliquam auctor eros ullamcorpernisi. ',
       category: 'ullamcorper'
    },
]