
export const faqs: Faq[] = [
    { id: 1,
       question: 'What types of cargo and freight does OAK & D handle?',
        answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
    },
    { id: 2,
        question: 'What is the cost of shipping goods with OAK & D?',
         answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
     },
     { id: 3,
        question: 'Can I track my shipment online? If so, how?',
         answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
     },
     { id: 4,
        question: 'What are the requirements for shipping hazardous',
         answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
     },
     { id: 5,
        question: 'What is the maximum weight and size limit for shipments',
         answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
     },
     { id: 6,
        question: '   Does OAK & D offer air or sea freight services?',
         answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
     },
     { id: 7,
        question: '  What is the process for scheduling shipment pickup ',
         answer: 'Lorem ipsum dolor sit amet consectetur. Cras nisi ultricies egestas suscipit aliquet. Senectus porta tortor morbi elit. Fames blandit sodales aliquet sit tincidunt ultrices. Tristique nisi ac feugiat purus consectetur. Id ut iaculis tristique odio malesuada tempus. Ornare eget varius arcu eu nibh imperdiet. ',
     },
]