export const shipData: ShipData[] = [
    {  id: 1,
       trackingId: '1000',
       shipment:'Dsxmr',
       type: 'Global',
       status: 'pending',
       ETA: {
            day: '1',
            month: '03',
            year: '2023',
       },
       departure: 'Toronto Canada',
       arrival: 'Lagos Nigeria',
       client : 'victor damascus',
       reciever:'Agatha thorn',
    },
    {  id: 2,
        trackingId: '1001',
        shipment:'Dsxmr',
        type: 'Domestic',
        status: '-in-Transit ',
        ETA: {
             day: '31',
             month: '05',
             year: '2023',
        },
        departure: 'Lagos Nigeria',
        arrival: 'Montreal Canada',
        client : 'Amanda Waller',
        reciever:'Halley Quin',
     },
     {  id: 3,
        trackingId: '1002',
        shipment:'Dsxmr',
        type: 'Global',
        status: 'Delayed',
        ETA: {
             day: '29',
             month: '09',
             year: '2023',
        },
        departure: 'Toronto Canada',
        arrival: 'Lagos Nigeria',
        client : 'Victor Stone',
        reciever:'Jonathan Kent',
     },
]