import Head from "next/head";
import styles from "@/styles/home.module.css";
import { useState } from "react";
import {
  About,
  Address,
  FAQ,
  GetStarted,
  Land,
  PageLayout,
  Testimonial,
  Why,
} from "@/components";
import { faqs } from "@/utils/faq";
import { OurLocation } from "@/components/DashboardComponent/SupportNavbar/OurLocation";

export default function Home() {
  return (
    <>
      <Head>
        <title>OAK & D LOGISTICS</title>
        {/* <link rel="icon" href="/img/nav-logo.svg" /> */}
        <link rel="icon" href="/img/fav-logo.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <PageLayout> 
            <main>
                <Land />
                <Why />
                <About />
                <Testimonial />
                {/* <div className='px-[50px]'>
          <Address />
          <FAQ faqs={faqs} />
          <GetStarted />
        </main>
      </PageLayout>
    </>
  );
}
