import Head from 'next/head'
import styles from '@/styles/home.module.css'
import { useState } from 'react'
import { About, Address, FAQ, GetStarted, Land, PageLayout, Testimonial, Why } from '@/components'
import { faqs } from '@/utils/faq'



export default function Home() {
  return (
    <>
      <Head>
        <title>OAK & D LOGISTICS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <PageLayout>
            <main>
                <Land />
                <Why />
                <About />
                <Testimonial />
                <Address />
                <FAQ faqs={faqs} />
                <GetStarted />
            </main>
        </PageLayout>
    </>
  )
}
